tasks:
  - before: |
      npm install
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      sudo apt-get install -q -y libunwind-dev
      sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
      sh -ci "npm i -g ic-mops"
      sh -ci "mops initi"
      sh -ci "dfx start --clean --background"
      sh -ci "dfx stop"

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
